DELETE http://localhost:3001/api/persons/4

###

GET http://localhost:3001/api/persons/67910688d45e1b300539031c

###

POST http://localhost:3001/api/persons/
content-Type: application/json

{
  "name": "rest client is a handy tools",
  "number": "eyyyys"
}

###
DELETE http://localhost:3001/api/persons/67910688d45e1b300539031c